# Generated by Django 5.0.4 on 2024-05-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(blank=True, null=True, upload_to='userphotos/', verbose_name='User Photo'),
        ),
    ]
